clc
clear
close all

load data_closeloop_qlye3step_40hr

figure()
subplot(6,2,1)
plot(qlye)
xlabel('Time, s')
ylabel('Lye flowrate, g/s')
subplot(6,2,3)
plot(V_El)
xlabel('Time, s')
ylabel('Cell voltage')
subplot(6,2,5)
plot(q_cw./1000)
xlabel('Time, s')
ylabel('q_{cw}, kg/s')
subplot(6,2,7)
plot(ZH2)
ylim([.4 .5])
xlabel('Time, s')
ylabel('z_{H_2}')
subplot(6,2,9)
plot(ZO2)
ylim([.4 .5])
xlabel('Time, s')
ylabel('z_{O_2}')
subplot(6,2,11)
plot(q_H2O./1000)
ylim([.28 .29])
xlabel('Time, s')
ylabel('q_{H_2O}, kg/s')
subplot(6,2,2)
plot(Temp)
xlabel('Time, s')
ylabel('T_k, [ ^0C]')
subplot(6,2,4)
plot(I_den)
xlabel('Time, s')
ylabel('I_{den}, mA/cm^2')
subplot(6,2,6)
plot(Telin)
ylim([49 51])
xlabel('Time, s')
ylabel('T_{El,in}, [ ^0C]')
subplot(6,2,8)
plot(PstoH2)
ylim([24 25])
xlabel('Time, s')
ylabel('p_{sto} H_2, bar')
subplot(6,2,10)
plot(PstoO2)
ylim([24 25])
xlabel('Time, s')
ylabel('p_{sto} O_2, bar')
subplot(6,2,12)
plot(mBufferT./1000)
ylim([2999 3001])
ylabel('Mass_{bt}, [kg]')
xlabel('Time, s')


figure()
subplot(2,3,1)
plot(Qnet(:,1))
xlabel('Time, s')
ylabel('Q_{net,1}')
subplot(2,3,2)
plot(Qnet(:,2))
xlabel('Time, s')
ylabel('Q_{net,2}')
subplot(2,3,3)
plot(Qnet(:,3))
xlabel('Time, s')
ylabel('Q_{net,3}')
subplot(2,3,4)
plot(Temp(:,1))
xlabel('Time, s')
ylabel('T_{el,1}')
subplot(2,3,5)
plot(Temp(:,2))
xlabel('Time, s')
ylabel('T_{el,2}')
subplot(2,3,6)
plot(Temp(:,3))
xlabel('Time, s')
ylabel('T_{el,3}')

for i=1:len
Q_overall(i) = sum(Qnet(i,:));
end
figure()
subplot(2,1,1)
plot(Q_overall)
xlabel('Time, s')
ylabel('Q_{net,sys}')
subplot(2,1,2)
plot(Telin)
xlabel('Time, s')
ylabel('T_{el,in}')