clc
clear
close all

load data_closeloop_qlye1step_40hr5MW


figure()
%plots for MVs qlye2 and qlye3 
subplot(2,2,1)
plot(qlye(:,2))
xlabel('Time, s')
ylabel('Lye flowrate El 2, g/s')
subplot(2,2,3)
plot(qlye(:,3))
xlabel('Time, s')
ylabel('Lye flowrate El 3, g/s')
%CVs
subplot(2,2,2)
plot(Temp(:,2))
xlabel('Time, s')
ylabel('T_2, [ ^0C]')
subplot(2,2,4)
plot(Temp(:,3))
xlabel('Time, s')
ylabel('T_3, [ ^0C]')

figure()
%plots for the qcw as MV
subplot(3,2,1)
plot(q_cw./1000)
xlabel('Time, s')
ylabel('q_{cw}, kg/s')
%CVs
subplot(3,2,2)
plot(Temp(:,1))
xlabel('Time, s')
ylabel('T_1, [ ^0C]')
subplot(3,2,4)
for i=1:length(Temp)
    TkGrad(i) = max(Temp(i,:))-Telin(i);
end
plot(TkGrad)
xlabel('Time, s')
ylabel('T_k-T_{El_{in}} const')
subplot(3,2,6)
plot(I_den(:,3))
xlabel('Time, s')
ylabel('I_{den,3}, mA/cm^2')

figure()
%plots for Vel as MV
subplot(2,2,1)
plot(V_El)
xlabel('Time, s')
ylabel('Voltage')
%CVs
subplot(2,2,2)
plot(I_den(:,1))
xlabel('Time, s')
ylabel('I_{den,1}, mA/cm^2')
subplot(2,2,4)
plot(P_net./1e6)
xlabel('Time, s')
ylabel('P_{net}, [MW]')

figure()
%plot for the states with zero ss effect
%MVs
subplot(3,2,1)
plot(ZH2)
ylim([.4 .5])
xlabel('Time, s')
ylabel('z_{H_2}')
subplot(3,2,3)
plot(ZO2)
ylim([.4 .5])
xlabel('Time, s')
ylabel('z_{O_2}')
subplot(3,2,5)
plot(q_H2O./1000)
xlabel('Time, s')
ylabel('q_{H_2O}, kg/s')
%CVs
subplot(3,2,2)
plot(PstoH2)
ylim([24 25])
xlabel('Time, s')
ylabel('p_{sto} H_2, bar')
subplot(3,2,4)
plot(PstoO2)
ylim([24 25])
xlabel('Time, s')
ylabel('p_{sto} O_2, bar')
subplot(3,2,6)
plot(mBufferT./1000)
ylim([2999 3001])
ylabel('Mass_{bt}, [kg]')
xlabel('Time, s')


% figure()
% subplot(2,3,1)
% plot(Qnet(:,1))
% xlabel('Time, s')
% ylabel('Q_{net,1}')
% subplot(2,3,2)
% plot(Qnet(:,2))
% xlabel('Time, s')
% ylabel('Q_{net,2}')
% subplot(2,3,3)
% plot(Qnet(:,3))
% xlabel('Time, s')
% ylabel('Q_{net,3}')
% subplot(2,3,4)
% plot(Temp(:,1))
% xlabel('Time, s')
% ylabel('T_{el,1}')
% subplot(2,3,5)
% plot(Temp(:,2))
% xlabel('Time, s')
% ylabel('T_{el,2}')
% subplot(2,3,6)
% plot(Temp(:,3))
% xlabel('Time, s')
% ylabel('T_{el,3}')

figure()
subplot(1,2,1)
plot(qlye(:,1))
xlabel('Time, s')
ylabel('Lye flowrate El 1, g/s')
subplot(1,2,2)
plot(Temp(:,1))
xlabel('Time, s')
ylabel('T_1, [ ^0C]')
